name: image_downloader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  html: ^0.15.4
  http: ^1.1.0
  meta: ^1.9.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
